### ISSUE TITLE
[Feature Request]Split visualize html files into multi html files

### ISSUE THREAD

**Issue by ybz21** [microsoft/promptflow#1354]
**Is your feature request related to a problem? Please describe.**
step1. run a batch test for a flow (200+ rows)
step2. run shell `pf run visualize -n xxx` 
the result html file is too big (1GB+, maybe there is to much logs in my flow) that the browser can not open it.

**Describe the solution you'd like**
it's better to save with the following rules:
1. save the batch summary in a main html file
2. save each test case's detail info in one html file, and put the link in the main html

**Comment by brynn-code** [comment]
@ybz21 Hi, could you please let us know the size of your input data?

**Comment by ybz21** [comment]
> @ybz21 Hi, could you please let us know the size of your input data?

219 rows, ervey rows just like
```
{"type": "positive", "exp_plugin_id": "xxxx", "exp_operation_id": "xxxx", "plugins": ["xxxx"], "messages": [{"role": "user", "content": "xxxxxxxxxxx?"}]}
```

**Comment by zhengfeiwang** [comment]
@ybz21 thanks for the information. The big HTML should result from the logs, and as we cannot view logs in visualize page, it is kind of reluctant data - we will remove it for now. For long-term, when we enable logs view, we will consider make those big data (e.g. logs) as separate file, and make that happen in JS, so that it won't block HTML loading and rendering.

The code change for removing logs in HTML is expected to happen in this week, and it should be shipped in next release.

**Comment by zhengfeiwang** [comment]
Hi @ybz21 , we have removed logs content in the HTML, so that it should be much smaller and you shall be able to visualize it. You can try `promptflow>=1.2.0` for the bug fix. Please let us know if you still run into some other problems.

Also, feel free to raise if you still expect the HTML split.
