### ISSUE TITLE
Better Output visualization

### ISSUE THREAD

**Issue by mces89** [microsoft/promptflow#1517]
Hi team,
    Currently I'm directly using the azure promptflow through web-broswer. However, the  flow's output is not great. For example, The '\n' doesn't visualized as line break but still character. Is there any way i can see them as real line breakers? Similarly For the json stuff. If the output is a json, is there any way to have a better visualization such as jq? Thanks.

**Comment by brynn-code** [comment]
@mces89 Could you please elaborate more about the web-broswer? Does it means the azure portal, or the github codespace? It would be better if you could attach an image to show us the output.

**Comment by mces89** [comment]
yeah, i mean in the azure portal. such as in the run/batch's result panel:
<img width="936" alt="Screenshot 2023-12-18 at 10 52 49 PM" src="https://github.com/microsoft/promptflow/assets/529149/f6b833ef-74b0-40db-b797-731a40379a29">
if both the input and output string has '\n', it cannot be seen as line break, still just '\n'?

**Comment by brynn-code** [comment]
@mces89 Got it. For the azure portal issue, please open the ocv(one customer voice) via the below face button, it will open a task and we'd like to track the azure version via inner task, the issue here mainly to track things related to open source promptflow, thank you.
![image](https://github.com/microsoft/promptflow/assets/24237253/adf245ce-b61b-44d7-9ee6-331dd7d4870e)

**Comment by brynn-code** [comment]
Close this issue as we only track open source version here.
