### ISSUE TITLE
[Feature Request] Add chat history buffer

### ISSUE THREAD

**Issue by Chukarslan** [microsoft/promptflow#1624]
Currently there is no way to dynamically add a max chat history buffer. The workaround is to write chat history to a db and check the db length before removing / appending new messages.

**Comment by 0mza987** [comment]
Hi @Chukarslan ,
Thanks for your feedback, since different users can have very different needs for chat history management, prompt flow has no plan to support chat history management in short term, customers are encouraged to use third-party tools to achieve this goal such as langchain chat history management, OpenAI threads or other methods like the DB you mentioned.
