### ISSUE TITLE
[Feature Request] Cycles support (or go to Graph processing)

### ISSUE THREAD

**Issue by ArtyomZemlyak** [microsoft/promptflow#1691]
**Is your feature request related to a problem? Please describe.**
Support cycles, not jast DAG executing.

**Describe the solution you'd like**
1. Extend DAG to graph of execution
2. Support cycles
3. Support over additional improvements for graph execution

**Describe alternatives you've considered**
Graph-executing engine of tasks - like a pipeline executor.

**Additional context**
Inspired: https://github.com/langchain-ai/langgraph

**Comment by D-W-** [comment]
Hi @ArtyomZemlyak , thanks for the suggestion. We have plan to launch a feature called "eager mode" which allows user to execute any python function with prompt flow and all prompt flow related features (test/batch run/evaluation/deploy) will be supported.
It doesn't look like langgraph because user don't need to define nodes & edges in this case. But cycles can be supported with python's built in loops like this:

```python
def entry_func(input: str):
    prev_responses = []
    while should_continue():
        response = llm_chat(input=input, prev_responses=prev_responses)
        prev_responses.append(response)
```

**Comment by ArtyomZemlyak** [comment]
@D-W- Thanks! Looks good!
