### ISSUE TITLE
Ability to set more advanced parameters on OpenAI, such as the seed

### ISSUE THREAD

**Issue by iceman3000** [microsoft/promptflow#2087]
**Is your feature request related to a problem? Please describe.**
The advanced parameters section on the openai tool doesn't include all advanced parameters, such as the seed.

**Describe the solution you'd like**
Include all advanced parameters as shown in the openai docs.

**Describe alternatives you've considered**
Using a custom python node and building openai calls manually.

**Comment by chjinche** [comment]
Hi @iceman3000 Thank you for bringing this to our attention. We're currently working on integrating the `seed` parameter into the LLM tool interface to enhance user control over generation consistency. 

However, for the time being, we might not include additional advanced parameters such as `logprobs`, `top_logprobs`, and `n`. This decision stems from our tool's design philosophy, which prioritizes delivering the first `choice` `message` output for seamless integration with downstream nodes, rather than the full API response. Altering this output structure would require a significant design overhaul and long-term planning. This means that such changes would significantly impact the downstream nodes in other users' flows and corresponding evaluation flows, necessitating adjustments across multiple areas.

Could you please specify any other specific parameters you're interested in, and explain why they are important for your use case? Your input could be invaluable in guiding our future updates.

**Comment by iceman3000** [comment]
Thanks. tools and tool_choice were both parameters I needed to use recently and could not via promptflow, with functions being deprecated.

**Comment by chjinche** [comment]
Hi @iceman3000, we have plan to support `tools` and `tool_choice` and deprecate `functions` and `function_call`. Will keep you informed when it is available to try.
