### ISSUE TITLE
Is there a way to have front end app chatting template like Azure Sampleaoai which consumes the endpoint? Need to do it with APP Service.

### ISSUE THREAD

**Issue by rehat22** [microsoft/promptflow#2403]

**Comment by 0mza987** [comment]
Hi @rehat22

Thanks for your feedback, can you please elaborate on your ask? What is the `Azure Sampleaoai` that is referencced in the titile, and how do you like the prompt flow to support it? It would be great if you can provide some code examples for us to learn about your user scenario, thanks.

**Comment by rehat22** [comment]
Azure Sampleaoai refers to this - https://github.com/microsoft/sample-app-aoai-chatGPT
We have deployed using the code from this repo. We basically wanted a front end like this which consumes the endpoint for users.
Basically we need a front end for consumers for our prompt flow end point which will be hosted on Azure APP service

**Comment by rehat22** [comment]
please let me know. Thank you

**Comment by 0mza987** [comment]
Your ask is a bit ambiguous and I'm trying to understand your scenario here. 

If you want a front ui for a developed flow then we do have an onging work to trigger one like this:
![image](https://github.com/microsoft/promptflow/assets/2572521/f04883de-c657-4385-83d4-ecc84f52e5cd)

If you want to share the flow to other customers then you can refer to [Distribute flow as executable app — Prompt flow documentation](https://microsoft.github.io/promptflow/how-to-guides/deploy-a-flow/distribute-flow-as-executable-app.html?highlight=executable)
 
Please let us know if above work satisfy your needs, otherwise please provide more details about how you would like promptflow to support, thanks.

**Comment by rehat22** [comment]
this solves my issue. The link provided is what i was looking for. Stream-lit will help me share the endpoint with customers. Im sure stream-lit can be replaced by AZURE APP Service to create the web app.
