### ISSUE TITLE
[BUG] pf run create does not output print statements to the console

### ISSUE THREAD

**Issue by aaronjolson** [microsoft/promptflow#2564]
**Describe the bug**
When invoking a pf run create command that fires off a flow, print statements inside of flow tools are not being output to the console or the logs.txt file

Example command: 
```
pf run create --name test_run1 --flow ./flow --data test_data.jsonl --stream
```
Where test_data.jsonl contains several lines of test input for bulk testing. The command runs without error.

**How To Reproduce the bug**
This bug occurs consistently. It can be reproduced by invoking a pf run create command that fires off a flow. The flow must contain at least 1 node that is a python tool that has a print() function inside of it that executes when that node is traversed.
Example command: 
```
pf run create --name test_run1 --flow ./flow --data test_data.jsonl --stream
```

**Expected behavior**
I would expect Python print() function calls to be output to the logs and console when executed during the run.

**Screenshots**
<img width="638" alt="Screenshot 2024-03-29 at 5 19 50 PM" src="https://github.com/microsoft/promptflow/assets/3924848/8b7e8d97-5ff4-4518-bf30-9bdab3c193a6">
<img width="1162" alt="Screenshot 2024-03-29 at 5 18 33 PM" src="https://github.com/microsoft/promptflow/assets/3924848/f585e74b-17e1-41e5-9793-1294571f9ffc">

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`:  1.6.0
 - Operating System: Mac OS 14.4.1
 - Python Version using `python --version`: python==3.10.6

**Comment by D-W-** [comment]
Hi @aaronjolson , this is our current by design behavior. Because when executing batch runs, multiple rounds of runs will be triggered based on different input lines, to avoid std out flood in terminal or in logs we only persist them in each line run's node artifacts. You can find them with the following steps:

1. Go to output path:
![image](https://github.com/microsoft/promptflow/assets/7776147/576813b2-c684-4f2d-aac3-84c51f3c957f)

2. Under `node_artifacts`, select the node, line run jsonl output:
![image](https://github.com/microsoft/promptflow/assets/7776147/0a40ef4e-b55a-4653-a88c-e7342ef70420)

3. Find the std out in `run_info.logs`

![image](https://github.com/microsoft/promptflow/assets/7776147/42f0188d-1172-4712-8c4d-003469f9b152)

**Comment by huaiyan** [comment]
Hello @aaronjolson, starting from version [1.7.0](https://pypi.org/project/promptflow/), except `node_artifacts`, a new option is finding each line's log under `flow_logs`.
We record customer print content as log with pattern `stdout>` and `stderr>` in there.

You can find them under `output_path` as @D-W-  mentioned.

![image](https://github.com/microsoft/promptflow/assets/17527303/ae812fbf-5407-44b1-bc70-b40873de50e7)
