### ISSUE TITLE
[BUG] Promptflow does not stream LLM response

### ISSUE THREAD

**Issue by giannisha** [microsoft/promptflow#2566]
**Describe the bug**
Not sure if this is an actual bug or promptflow limitation. In the following scenario I want to stream the generated text from the `llm` node, right to the **output** and then, clients start receiving it asap. Once the generation is completed I want the response to be saved in a cache. In this example the Python node `cache` only sleep waits for 20 sec.

![image](https://github.com/microsoft/promptflow/assets/153095545/111d5ff9-f11f-4cd4-ae76-f287d3e00dfb)

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug: Always
1. Create an LLM node using Open AI GPT-4
2. Pass LLM output to promptflow output
3. Pass LLM output to the `cache` Python node

**Expected behavior**
Client start receiving events as soon as the first chunks are generated in the `llm` node (if `Accept: text/event-stream` header has been used). `cache` Python node be executed after the LLM generation completed

**Screenshots**
`application/json` response: 200 OK, waiting also for Python node to finish. Not ideal
`text/event-stream` response: 406 NOT ACCEPTABLE (screenshot below). In the logs you can see the answer already generated.

![image](https://github.com/microsoft/promptflow/assets/153095545/7e09805e-1e88-4e18-8f48-b6490dddb921)

**Running Information**
 - Promptflow Package Version using `pf -v`: 1.6.0
 - Operating System: `docker.io/continuumio/miniconda3:latest`
 - Python Version using `python --version`: 3.11.7

Is there any other way to achieve what I describe above?

**Comment by liucheng-ms** [comment]
Hi @giannisha 

Thank you for bringing up this issue related to streaming behavior in PromptFlow. I appreciate your attention to detail and your desire to improve the system.

Upon reviewing your scenario, it seems that there might be some confusion regarding the streaming functionality within PromptFlow. To help clarify, I'd like to direct you to our comprehensive documentation on streaming mode here: [Enable streaming mode in Azure Machine Learning](https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/how-to-enable-streaming-mode?view=azureml-api-2).

As per the current design of PromptFlow, streaming is only supported by the output of the final node in a given flow. The term "last node" specifically refers to a node whose output is not utilized by any subsequent nodes in the workflow. 

In the scenario you've described, the output of the llm node is being passed on to a cache Python node. This interconnection implies that the llm node is not the last node in your flow, hence it does not satisfy the criteria for streaming its output.

To achieve the behavior you expect, you would need to adjust your flow so that the `streaming` node is the final node, thus allowing its output to be streamed directly to your clients. Any subsequent actions, such as caching, would then need to be managed independently outside of the PromptFlow sequence.

If you have any further questions or need additional clarification, feel free to reach out. Feedback is highly appreciated.

**Comment by giannisha** [comment]
Hi @liucheng-ms

Thank you very much for your detailed response.
Do you think this scenario, to have nodes detached from the main flow, would be good to be supported in the future?
For similar cases, or other cases where you want to fire something and forget it (cache, logs.

**Comment by liucheng-ms** [comment]
Hi @giannisha ,

I understand your request for a feature that allows nodes to be detached from the main flow, enabling actions like caching or logging to be executed independently. Your suggestion for “fire and forget” functionality could indeed be beneficial for certain use cases.

Currently, we do not have immediate plans to support this feature within PromptFlow’s scope. However, we recognize the potential value it could offer. We will consider the need for such a feature and evaluate whether it aligns with our design principles and priorities.

Thank you for your feedback, and please continue to share your thoughts and ideas with us.

**Comment by giannisha** [comment]
Great! Thank you very much for your feedback @liucheng-ms!
