### ISSUE TITLE
[BUG] - promptflow 1.10.1 incompatible with azure-cli

### ISSUE THREAD

**Issue by marinaby** [microsoft/promptflow#3094]
promptflow 1.10.1 incompatible with azure-cli

1. Add to requirements of python project:
promptflow==1.10.0
azure-cli==2.60.0

2. Try to install requirements

Expected behavior: 
Both successfully installed

Actual behaviour:
Failed to install due to conflict:
The conflict is caused by:
    azure-cli-core 2.60.0 depends on argcomplete~=3.1.1
    promptflow-devkit 1.9.0 depends on argcomplete>=3.2.3

 - Promptflow Package Version using `pf -v`: 1.10.1
 - Operating System: macos
 - Python Version using : Python 3.9.18

**Comment by elliotzh** [comment]
Hi @marinaby 

Thank you for reporting this. I have checked related pull requests:
azure-cli: [{Packaging} Bump argcomplete to 3.1.1](https://github.com/Azure/azure-cli/pull/26684)
promptflow: [[SDK/CLI] added autocompletion for pf cli](https://github.com/microsoft/promptflow/pull/2534)

According to the pull requests:
1. `azure-cli` and `promptflow` doesn't depend on each other; 
2. `azure-cli` ping an old version of `argcomplete` just because it will ping a specific version for all of its dependencies, so no break is expected if you install `azure-cli` first and then `promptflow`;
3. given `azure-cli` has ping a specific version, not sure if it's a better idea to bump `argcomplete` in `azure-cli`.

Please tell us if any further usage is broken. And we will have an inner discussion on whether promptflow should fit requirements of `azure-cli`.
