### ISSUE TITLE
[BUG] Cannot resolve connection value from OS environments

### ISSUE THREAD

**Issue by firgavin** [microsoft/promptflow#3330]
**Describe the bug**
I attempted to deploy a flow using Docker, so I followed the documentation and replaced the connection's api_key field with ${env:OPEN_AI_CONNECTION_API_KEY}. Then, I ran the Docker container with the corresponding environment variable, but the flow failed due to an OpenAI Unauthorized error. After enabling OpenAI client debugging, I discovered that the api_key template was present in the request.

**How To Reproduce the bug**
This is a consistently reproducible issue.
1. Prepare a connection YAML file with an environment variable reference.
```
$schema:
  https://azuremlschemas.azureedge.net/promptflow/latest/AzureOpenAIConnection.schema.json
type: azure_open_ai
name: open_ai_connection
module: promptflow.connections
api_base: https://fake.openai.azure.com/
api_key: ${env:OPEN_AI_CONNECTION_API_KEY}
api_type: azure
api_version: '2024-02-01'
auth_mode: key
```
2. Invoke this connection in a basic chat flow.
3. Run "export OPENAI_LOG=debug".
4. Run "pf flow test --flow flow --inputs question=hello".

The flow then fails, and the following message appears:
```
pf.flow.test failed with UserErrorException: Exception: OpenAI API hits AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'} [Error reference: https://platform.openai.com/docs/guides/error-codes/api-errors]
```

**Expected behavior**
Connection value in "${env:KEY}" format should be resolved from OS environments.

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
```
$ pf version
{
  "promptflow": "1.11.0",
  "promptflow-core": "1.11.0",
  "promptflow-devkit": "1.11.0",
  "promptflow-tracing": "1.11.0"
}
```

 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
```
$ sw_vers
ProductName:		macOS
ProductVersion:		13.6.3
BuildVersion:		22G436
```

 - Python Version using `python --version`: [e.g. python==3.10.12]
```
$ python --version
Python 3.10.14
```
**Additional context**

I am trying to identify this problem and propose that templates in the connection values should be rendered in DictConnectionProvider when constructing the ToolResolver. See [link](https://github.com/microsoft/promptflow/blob/main/src/promptflow-core/promptflow/executor/flow_executor.py#L288C27-L288C49).
I am very much looking forward to a prompt resolution of this issue, and I am also very willing to contribute code to fix the problem if possible. Looking forward to any feedback.

**Comment by brynn-code** [comment]
Hi @firgavin, thanks for reaching us, actually in the #3236 we have a friend raise the similar problem with you, but I didn't reproduce the problem.
If you are using dockerfile exported by 'pf flow build', could you please check the connection file from the output directory? My test output looks like:
![image](https://github.com/microsoft/promptflow/assets/24237253/4f473b45-66ad-4b8a-9453-3c17f37b1039)
And I ran it with `docker run -p 8080:8080 -e AZURE_OPEN_AI_CONNECTION_API_KEY=.... name`, the flow can return result successfully.

**Comment by firgavin** [comment]
@brynn-code Thank you for check this issue. I did search through all open issues but somehow missed that particular one. I've noticed that this feature works correctly only with 'flow serve', as you mentioned in https://github.com/microsoft/promptflow/issues/3236. However, I'm curious why it doesn't work similarly for 'flow test' or 'flow run'? In my scenario, I need to use "flow run" with the same connection management in this container.

**Comment by brynn-code** [comment]
At the early stages of design, we introduced this for 'flow serve' is because we'd like user have a more fluent experience when deploying the flow, as it is frustrated if they need to deploy to several region and then create connection for each one, it will be better if they only have to configure environment variables for each deployment.

For the 'flow test' and 'flow run', usually we assuming that user is doing this locally on their machine, they are still authoring the flow, in this case, we encourage user leverage our connection to store api keys, the stored key was encryted, and encryption key  was managed by system ( for example, in windows we will store encrytion key to Credential Manager ), and promptflow will not stored the value.
![image](https://github.com/microsoft/promptflow/assets/24237253/8e732dd0-ade5-4955-9666-bd66d81667eb)

Please be careful about it, if user remove it manually, then they can't use connection anymore as promptflow can't decrypt existing connections, unless delete the whole sqlite db.
