### ISSUE TITLE
Invalid instrumentation key

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/promptflow#3373]
**Describe the bug**

I am following this tutorial: https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/how-to-trace-local-sdk?view=azureml-api-2&tabs=python

I logged in using azure cli and then entered the command to set up my trace destination:
pf config set trace.destination=azureml://subscriptions/<your_subscription_id>/resourcegroups/<your_resourcegroup_name>/providers/Microsoft.MachineLearningServices/workspaces//<your_azureml_workspace_name>

This created a CosmosDB.  I promptflow does not do this every time I run it on different machines.

I tried to send traces using the trace-autogen-groupchat.ipynb, and I got this error:

ERROR:opencensus.ext.azure.common.transport:Non-retryable server side error 400: {"itemsReceived":2,"itemsAccepted":0,"appId":null,"errors":[{"index":0,"statusCode":400,"message":"Invalid instrumentation key"},{"index":1,"statusCode":400,"message":"Invalid instrumentation key"}]}.
ERROR:opencensus.ext.azure.common.transport:Non-retryable server side error 400: {"itemsReceived":1,"itemsAccepted":0,"appId":null,"errors":[{"index":0,"statusCode":400,"message":"Invalid instrumentation key"}]}.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Download the trace-autogen-groupchat.ipynb notebook from this repo
2. Follow the instructions for setting the trace destination https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/how-to-trace-local-sdk?view=azureml-api-2&tabs=python
3. Try to run the code in the autogen section, where agents generate messages and send them using tracing.

**Expected behavior**
I expected the information to be sent without any error.

Using Windows, Python 11, and the latest version of PromptFlow.

**Comment by zhengfeiwang** [comment]
Hi @tyler-suard-parker , thank you for reaching out. I think there are several questions in this issue:

- `pf config set trace.destination` does create a Cosmos DB, but one workspace will only have one Cosmos resource, so I understand when you run same command on different machines, only the first time you will see the Cosmos setup process (and wait for that).
- For the error, it's wired to me because we did use `opencensus` before, but in #2175 , which is merged 3 months ago, we already migrate to Open Telemetry. Could you please share some screenshots for your error? and provide your prompt flow version with `pf -v`? so that maybe we can re-produce your error and better investigate on that.
