### ISSUE TITLE
Deploy fails to Azure Container Apps

### ISSUE THREAD

**Issue by vieiraae** [microsoft/promptflow#3444]
**Describe the bug**
When deploying the docker image into Container Apps the container fails with the following error:
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \u0022bash start.sh\u0022: executable file not found in $PATH: unknown

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Build the container image
2. Deploy on Container Apps
3. Check the logs

**Expected behavior**
I expected the container to run :)
If I change the lastline from the Dockerfile from
CMD ["bash", "./start.sh"] 
> to
CMD ["/bin/bash", "./start.sh"] 

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
PS C:\Projects\AI-Gateway\labs\prompt-flow> pf -v
{
  "promptflow": "1.12.0",
  "promptflow-azure": "1.12.0",
  "promptflow-core": "1.12.0",
  "promptflow-devkit": "1.12.0",
  "promptflow-tracing": "1.12.0"
}

Executable 'C:\Users\alexviei\AppData\Local\Programs\Python\Python312\python.exe'
Python (Windows) 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
 - Operating System: Windows 11
 - Python Version using `python --version`: Python 3.12.2

**Additional context**
The issue can be simple fixed just by changing the last line of the generated Dockerfile to:
CMD ["/bin/bash", "./start.sh"]

**Comment by brynn-code** [comment]
@vieiraae Hi, thanks for reaching us. For most of the scenarios, '/bin/bash' will be in the system $PATH. Meanwhile, it will be more flexible to use the 'bash' as sometimes user may wanna use some other choices instead of '/bin/bash'. 

So we would like to keep the 'bash' in command, and for your case, adding '/bin/bash' to system $PATH should work, and we're wondering about your environment, which kind of system are you using in the container?
