### ISSUE TITLE
[BUG] Documentation not according to actual API spec

### ISSUE THREAD

**Issue by dunnkers** [microsoft/promptflow#3468]
**Describe the bug**
On this docs page in Function based flow: https://microsoft.github.io/promptflow/how-to-guides/develop-a-flex-flow/function-based-flow.html#batch-run

... the docs say you can use the following code:

```
from path.to.module import my_flow
pf.run(flow=my_flow, data="./data.json;")
```

But that is actually clearly not implemented in the code on `main`:

https://github.com/microsoft/promptflow/blob/2eb9cb41fb04460ebe8790713b25decc799081a8/src/promptflow-azure/promptflow/azure/_pf_client.py#L289-L290

So we will want to: either update the docs or implement the functionality 😇

**Comment by D-W-** [comment]
Hi @dunnkers , sorry for the misleading. The document refers to the local PFClient. For the local PFClient, we support executing a function as a flow. However, for the cloud PFClient, we currently do not support this feature. Because it's hard to determine all dependencies for the function and upload them to cloud. For local case, it's much easier since we can just reuse local environment.

Here's local PFClient's code for your reference: 
https://github.com/microsoft/promptflow/blob/2eb9cb41fb04460ebe8790713b25decc799081a8/src/promptflow-devkit/promptflow/_sdk/_pf_client.py
You can create one with the following code:

```
from promptflow.client import PFClient
pf = PFClient()
```

**Comment by dunnkers** [comment]
hi! Ah okay I understand now. Thanks for the answer. Maybe we can clarify that in the docs?

**Comment by D-W-** [comment]
Sure, we'll use this issue to track the doc update.

**Comment by dunnkers** [comment]
awesome , thx for the update @D-W- !
