### ISSUE TITLE
Failed to load trace[BUG]

### ISSUE THREAD

**Issue by huqianghui** [microsoft/promptflow#3540]
**Describe the bug**
I have run the flow in my vscode by command or the UI。
The trace url was printed in the console.
I trid to click the url, then get the error.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Run the flow in the vscode

**Expected behavior**
The trace log could be shown in the page.

**Screenshots**
<img width="1406" alt="Screenshot 2024-07-11 at 6 51 58 PM" src="https://github.com/microsoft/promptflow/assets/7360524/ac6143d9-2603-4baa-b8ba-9e846dcfe663">

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 
{
  "promptflow": "1.13.0",
  "promptflow-core": "1.13.0",
  "promptflow-devkit": "1.13.0",
  "promptflow-tracing": "1.13.0"
}

 - Python Version using `python --version`: [e.g. python==3.10.12]
Executable '/Users/huqianghui/Downloads/books-translations/.venv/bin/python'
Python 3.11.9

 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - MacOS

**Additional context**
when I run another flow in the workspace，the port is 23334 not the 23333.
And it works well.
<img width="1424" alt="Screenshot 2024-07-11 at 6 53 06 PM" src="https://github.com/microsoft/promptflow/assets/7360524/881958fc-2c2d-40cf-a8ee-b11f7887f938">

question:
How to fix the issue? or change the port mannually?

**Comment by zhengfeiwang** [comment]
Hi @huqianghui , thanks for reaching out! According to your screenshot, you are openning a trace ui page for specific trace, as there is a trace id in the url, and you get errors. The reason behind varies, so we might need more inputs from your side:

- Could you please provide the error message in those 500 responses? We cannot say what's the root cause without seeing this.
- If possible, provide prompt flow service, which hosts tracing related APIs, logs; you can get the log file location via command `pf service status`, so that we can better understand what happened.

**Comment by huqianghui** [comment]
@zhengfeiwang ，thanks for your response. I tried to restart my compute, then it works well.
And I try the same traceId in the UI, it also works well now.

And I just want to how to config the trace service, like the port or the storage?

Is there sample rate to config and so no?

**Comment by zhengfeiwang** [comment]
had offline sync with Qianghui and got his pfs log file, we will take a look to avoid similar issue in the future.
