### ISSUE TITLE
[BUG] Codespaces: To create Connections, keyrings.alt needs to be installed

### ISSUE THREAD

**Issue by mor10** [microsoft/promptflow#3673]
**Describe the bug**
In Codespaces, if you try to create a connection you get an error because the system can't store a local environment variable.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a new OpenAI Connection
2. Add the OpenAI API key
3. The terminal, it overfloweth with errors aplenty

**How To Fix**
Add `keyrings.alt` to `requirements.txt`

**Comment by D-W-** [comment]
Hi @mor10 , thanks for reporting this. We already added it to our [doc](https://microsoft.github.io/promptflow/how-to-guides/faq.html#connection-creation-failed-with-storeconnectionencryptionkeyerror). 
The reason we did not add it to `requirements.txt` is because it's not required in Windows and MacOS as doc describes.

**Comment by mor10** [comment]
Since you have the GitHub Codespaces button right up front, I recommend adding it in to avoid people tripping over it. Alternately make a dedicated codespaces branch with this variant so you don't have that conflict.

**Comment by D-W-** [comment]
Got it, we'll add it in the Codespaces's image.
