### ISSUE TITLE
[BUG] Missing apiType error when creating Cognitive Search Prompt Flow connection using the UI

### ISSUE THREAD

**Issue by marcalap** [microsoft/promptflow#564]
**Describe the bug**
When creating a new "Add Cognitive search connection" in prompt flow UI, we get a 400 bad request with this message: 
"Required metadata property ApiType is missing". 
When we look at the openAI connection, it does have an "apiType" textBox, but not for Cognitive Search. Not sure while it would be required anyway.
I manually modified the payload to include "api_type":"azure" but I still get the exact same error message.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. In prompt flow UI, try to create a new Cognitive search connection. It fails everytime.

**Expected behavior**
Successfully Add a Cognitive Search connection in prompt flow without having to specify apiType.

**Screenshots**
![Screenshot 2023-09-19 at 7 49 51 AM](https://github.com/microsoft/promptflow/assets/45609587/9a08065f-2409-4497-b007-6e33ffd6bd32)

**Comment by wyl765** [comment]
@marcalap since here is to track the issue of the open source version of prompt flow, the issue reported is about AML Studio portal. Could you help open ocv through the portal UI. I will also try if I can repro from my side in portal. Thanks a lot!
<img width="778" alt="image" src="https://github.com/microsoft/promptflow/assets/834505/a92af30e-7ff1-4c7c-b28d-ab351eacdd01">

**Comment by marcalap** [comment]
Thanks. 
it's fixed.
