### ISSUE TITLE
[Feature Request] Copy a node

### ISSUE THREAD

**Issue by Anbang-Hu** [microsoft/promptflow#717]
**Is your feature request related to a problem? Please describe.**
We want to copy an existing node and make updates to the input parameters in visual editor.

**Describe the solution you'd like**
Add an icon for duplicating a node for editing.

**Describe alternatives you've considered**
Right now, the workaround is to search for the unique node name (obtained from visual editor) in `flow.dag.yaml`, and make a copy of it in `flow.dag.yaml`.

**Additional context**
NA

**Comment by jiaochenlu** [comment]
If you wish to **create a new node that references an existing file**, whether it's a Jinja or Python file, this functionality is already available in the Visual Studio Code extension.
![image](https://github.com/microsoft/promptflow/assets/32232238/d2c55374-a901-4e9b-9658-fafd22c0210a)

However, if you're looking to make a copy of this file for personalized modifications instead of referencing the same one, that would be a different scenario. From your description, seems like you are this pattern, but your workaroud which to do the yaml copy will still refer to the same file. 

and what kind of modification you'd like to do on input parameters after copy, only the parameter name? some parameter change need the file content change as well
