### ISSUE TITLE
[Feature Request] [CLI] "pf flow init" to support "Azure connected" flow better

### ISSUE THREAD

**Issue by ttthree** [microsoft/promptflow#752]
In "Azure connected" flow there are a few changes might be needed (and make sense):

1. The connection yaml files shouldn't be generated.
2. The connection name and deployment name in the flow.dag.yaml can be override instead of hard code ones.

**Comment by eniac871** [comment]
So IIUC, the expect behavior:
For No.1  When run pf flow init, and when we need to create connection yaml, firstly check whether the connection provider config point to Azure, if so, don't generate local connection yaml file
For No.2 , do you mean we provide CLI parameter to let user override when run pf flow init?

**Comment by ttthree** [comment]
yes, to both questions.

**Comment by eniac871** [comment]
Discussed this feature request, here're some proposal plan: 

We plan to provide 2 parameters to set connection : --connection <connectionName>, --deployment <deploymentName>. These will be hidden parameter but available to use through CLI. 
And the overall expected behavior when different connection provider set: 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/anthu/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/anthu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">



Connection Provider | No connection/parameter | Has connection/deployment parameter
-- | -- | --
Azure | Don't create local connection | Don't create local connection, Set the connection/deployment in   flow.dag.yaml
local | Create local connection.yaml | Create local connection.yaml, Set the connection/deployment in   flow.dag.yaml , set connection name in connection.yaml



</body>

</html>
