### ISSUE TITLE
[BUG] "Error when parsing request" when submitting a run with pfazure

### ISSUE THREAD

**Issue by danigian** [microsoft/promptflow#841]
**Describe the bug**
When submitting a run with pfazure, if the "name"/"runId" includes the ':' character, a 400 is returned from the server.

**How To Reproduce the bug**
100% reproducible when:
1. Creating a run with pfazure run create --name "SomeRunWith:CharacterInside"

**Expected behavior**
The pfazure CLI should check for not allowed characters in the name/runId and fail immediately with a proper error message.

**Screenshots**
![image](https://github.com/microsoft/promptflow/assets/1955514/3888dae4-bb82-4a9b-a6d8-bcf52272bb61)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 0.1.0b7.post1
 - Operating System: Debian Bullseye
 - Python Version using `python --version`: Python 3.11.6

**Comment by D-W-** [comment]
Hi @danigian, our service has released a fix to all regions for this issue and will return a user error in that case on name/runId's restrictions: 
![image](https://github.com/microsoft/promptflow/assets/7776147/ef580c49-582f-4178-80c7-d29d6f126086)
Please help verify if it works on your side.

**Comment by danigian** [comment]
I could not yet verify this but, in the meanwhile, why not checking this kind of limits before submitting the actual run? @D-W-

**Comment by D-W-** [comment]
Hi @danigian , after our fix, the run won't be created if name/run id 's invalid. 
We added the check in service side instead of client side is because the run name restriction is defined in service side and it's better to put the check logic near the definition. Putting the check in client side will also bring other roll-out issues like if we want to change the limitation, we'd need users to upgrade to pick up the change.
But I do agree we should have client side validation to prevent illegal run's submission to service side, we have a feature tracking it.

**Comment by danigian** [comment]
Thanks for the explanation. Closing the issue 👍
